routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('template.partials.content');
})->name('dashboard');

Route::prefix('post')->name('post.')->controller(PostController::class)->group(function (){
    Route::get('/','index')->name('index');
    Route::get('/create','create')->name('create');
    Route::post('/store','store')->name('store');
    Route::get('/edit/{id}','edit')->name('edit');
    Route::put('/update/{id}','update')->name('update');
    Route::get('/destroy/{id}','destroy')->name('destroy');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title','description','content','status'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Post\PostRequest;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }

    /**
     * Display a listing of the resource.
     * @return mixed
     */
    public function index()
    {
        $posts = $this->post->paginate(7);
        return view('template.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     * @return mixed
     */
    public function create()
    {
        return view('template.post.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param PostRequest $request
     * @return mixed
     */
    public function store(PostRequest $request)
    {
        $dataStore = $request->all();
        $this->post->create($dataStore);
        return redirect()->route('post.index')->with(['message'=>'Create New Post Successfully']);
    }

    /**
     * Show the form for editing the specified resource.
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $post = $this->post->findOrFail($id);
        return view('template.post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     * @param PostRequest $request
     * @param $id
     * @return mixed
     */
    public function update(PostRequest $request, $id)
    {
        $post = $this->post->findOrFail($id);
        $dataUpdate = $request->all();
        $post->update($dataUpdate);
        return redirect()->route('post.index')->with(['message'=>'Update Post Successfully']);
    }

    /**
     * Remove the specified resource from storage.
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $post = $this->post->findOrFail($id);
        $post->delete();
        return redirect()->route('post.index')->with(['message'=>'Delete Post Successfully']);
    }
}

resources/views/template/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
@yield('title')

<!-- plugins:css -->
    <link rel="stylesheet" href="{{asset('theme/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('theme/vendors/base/vendor.bundle.base.css')}}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{asset('theme/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{asset('theme/css/style.css')}}">
{{--    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}">--}}
    <!-- endinject -->
    <link rel="shortcut icon" href="{{asset('theme/images/favicon.png')}}"/>

</head>

<body>
<!-- partial:partials/_navbar.html -->
@include('template.partials.navbar')
<!-- partial -->
<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_sidebar.html -->
@include('template.partials.sidebar')
<!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            @yield('content')
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
    @include('template.partials.footer')
    <!-- partial -->
    </div>
    <!-- main-panel ends -->
</div>
<!-- page-body-wrapper ends -->
<!-- container-scroller -->

<!-- plugins:js -->
<script src="{{asset('theme/vendors/base/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="{{asset('theme/vendors/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('theme/vendors/datatables.net/jquery.dataTables.js')}}"></script>
<script src="{{asset('theme/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{asset('theme/js/off-canvas.js')}}"></script>
<script src="{{asset('theme/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('theme/js/template.js')}}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{{asset('theme/js/dashboard.js')}}"></script>
<script src="{{asset('theme/js/data-table.js')}}"></script>
<script src="{{asset('theme/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('theme/js/dataTables.bootstrap4.js')}}"></script>
<!-- End custom js for this page-->

<script src="{{asset('theme/js/jquery.cookie.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/js/bootstrap.js')}}"></script>
</body>

</html>

resources/views/template/partials/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © <a
                    href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best <a
                href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard </a> templates</span>
    </div>
</footer>

resources/views/template/partials/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
            <a class="navbar-brand brand-logo" href="index.html"><img src="{{asset('theme/images/logo.svg')}}" alt="logo" /></a>
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{asset('theme/images/logo-mini.svg')}}" alt="logo" /></a>
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-sort-variant"></span>
            </button>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
            <li class="nav-item nav-search d-none d-lg-block w-100">
                <div class="input-group">
                    <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search now" aria-label="search"
                           aria-describedby="search">
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
                    <img src="{{asset('theme/images/faces/face5.jpg')}}" alt="profile" />
                    <span class="nav-profile-name">Louis Barnett</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item">
                        <i class="mdi mdi-settings text-primary"></i>
                        Settings
                    </a>
                    <a class="dropdown-item">
                        <i class="mdi mdi-logout text-primary"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/template/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{route('dashboard')}}">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('post.index')}}">
                <i class="mdi mdi-book-open-variant menu-icon"></i>
                <span class="menu-title">Post</span>
            </a>
        </li>
    </ul>
</nav>

resources/views/template/post/create.blade.php
@extends('template.dashboard')
@section('title')
    <title>Create Post</title>
@endsection
@section('content')
    <div class="card">
        <h5 class="card-header">Create Post</h5>
        <div class="card-body">
            <form action="{{route('post.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label >Title</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{old('title')}}">
                    @error('title')
                    <div class="alert text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >Description</label>
                    <textarea type="text" class="form-control @error('description') is-invalid @enderror" name="description">{{old('description')}}</textarea>
                    @error('description')
                    <div class="alert text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >Content</label>
                    <textarea type="text" class="form-control @error('content') is-invalid @enderror" name="content">{{old('content')}}</textarea>
                    @error('content')
                    <div class="alert text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <input type="radio" name="status" value="0" class="mx-2" id="status0" class="status">
                    <label for="status0">Hide</label>
                    <input type="radio" name="status" value="1" class="mx-2" id="status1" class="status">
                    <label for="status1">Visible</label>
                    @error('status')
                    <div class="alert text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button class="btn btn-primary text-white" type="submit">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/template/post/edit.blade.php
@extends('template.dashboard')
@section('title')
    <title>Edit Post</title>
@endsection
@section('content')
    <div class="card">
        <h5 class="card-header">Edit Post</h5>
        <div class="card-body">
            <form action="{{route('post.update',['id'=>$post->id])}}" method="POST">
                @csrf
                @method('put')
                <div class="form-group">
                    <label >Title</label>
                    <input type="text" class="form-control" name="title" value="{{$post->title}}">
                </div>
                <div class="form-group">
                    <label >Description</label>
                    <textarea type="text" class="form-control" name="description">{{$post->description}}</textarea>
                </div>
                <div class="form-group">
                    <label >Content</label>
                    <textarea type="text" class="form-control" name="content">{{$post->content}}</textarea>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <input type="radio" name="status" value="0" class="mx-2" id="status0" {{$post->status=='0'?'checked':''}}>
                    <label for="status0">Hide</label>
                    <input type="radio" name="status" value="1" class="mx-2" id="status1" {{$post->status=='1'?'checked':''}}>
                    <label for="status1">Visible</label>
                </div>
                <button class="btn btn-primary text-white" type="submit">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/template/post/index.blade.php
@extends('template.dashboard')
@section('title')
    <title>View Post</title>
@endsection
@section('content')
    <div class="card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h4 class="d-block">View Post</h4>
            <a href="{{route('post.create')}}" class="btn btn-primary btn-sm text-white d-block">Add Post</a>

        </div>
        <div class="card-body">
            @if(session('message'))
                <span class="text-success">{{session('message')}}</span>
            @endif
            <table class="table table-bordered table-striped table-bordered table-hover">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Content</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($posts as $post)
                <tr>
                    <th scope="row">{{$post->id}}</th>
                    <td>{{$post->title}}</td>
                    <td>{{$post->description}}</td>
                    <td>{{$post->content}}</td>
                    <td>{{$post->status=='0'?"Hide":'Visible'}}</td>
                    <td>
                        <a href="{{route('post.edit',['id'=>$post->id])}}" class="btn btn-sm btn-warning text-white">Edit</a>
                        <a href="{{route('post.destroy',['id'=>$post->id])}}" class="btn btn-sm btn-danger text-white" onclick="return confirm('Are you sure?')">Delete</a>
                    </td>
                </tr>
                @empty
                    <tr >
                        <td colspan="6">No Post Found!!!!</td>
                    </tr>
                @endforelse
                </tbody>

            </table>
                {{$posts->links()}}
        </div>
    </div>

@endsection